-- Invites (ROADMAP Phase 4 / F6).
-- Run AFTER 0001–0027 on a project with Supabase Auth enabled.
--
-- WHAT THIS IS NOT: invite-GATED signup. The roadmap asked for Beli's loop —
-- codes as a scarcity mechanic that turns joining into a privilege. That works
-- when there is a queue at the door. Jelli's stated goal is ad revenue, which is
-- impressions, which is people; turning away everyone without a code would
-- optimise for exclusivity at the direct expense of the thing being optimised
-- for. Scarcity is a lever you pull once demand exists, and it can be pulled
-- later by making `redeem_invite` mandatory at signup — the schema below already
-- supports that day.
--
-- WHAT IT IS: a referral link that seeds the follow graph. The first thing a new
-- account sees is an empty feed, and an empty feed is the single most common way
-- a social app fails on day one (goal #3: every action emits an event and every
-- feed event can be reacted to — worth nothing if you follow nobody). Arriving
-- through a friend's link means arriving already connected to at least one
-- person, mutually, before the app has to ask you to search for strangers.
--
-- WHY A CODE AND NOT JUST /user/<uuid>: a code is short enough to say out loud
-- and carries no account id, so a shared link doesn't publish anyone's uid. It
-- is also revocable and countable, which is what makes "3 invites left" a real
-- number rather than a decoration.

create table if not exists public.invites (
  -- Short, human-sayable, unambiguous. Generated by the function below.
  code        text primary key,
  inviter_id  text not null,
  -- Null until someone joins with it. One redemption per code, enforced by the
  -- unique index below rather than by trusting the client to stop asking.
  invitee_id  text,
  created_at  timestamptz not null default now(),
  redeemed_at timestamptz,
  -- Belt to the braces on redeem_invite's own check: the two can never be equal.
  check (invitee_id is null or invitee_id <> inviter_id)
);

create index if not exists invites_inviter_idx on public.invites (inviter_id, redeemed_at);

alter table public.invites enable row level security;

-- You can see the codes you handed out (to show "3 left" and who joined).
drop policy if exists "read own invites" on public.invites;
create policy "read own invites" on public.invites for select
  using (auth.uid()::text = inviter_id);

-- Note there is deliberately NO policy letting a client select by code. A public
-- read would let anyone enumerate the table and burn every outstanding invite —
-- and a code is a bearer token, so being able to *look one up* is being able to
-- use it. Redemption goes through the SECURITY DEFINER function below, which is
-- the only thing that ever reads a code it wasn't given.

-- Codes are minted by a function, not inserted by the client: the client cannot
-- be trusted to enforce a per-user cap on rows it creates itself.
drop policy if exists "no client invite writes" on public.invites;

-- ============================================================
-- Minting
-- ============================================================
-- Excludes I/O/0/1 — a code that has to be read off a screen and typed into a
-- phone should not contain characters that argue about which one they are.
create or replace function public.generate_invite_code()
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  result text;
  i int;
begin
  loop
    result := '';
    for i in 1..6 loop
      result := result || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    -- 32^6 ≈ 1e9, so a collision is rare — but "rare" is not "never", and a
    -- primary-key violation on someone's first tap is a bad way to find out.
    exit when not exists (select 1 from public.invites where code = result);
  end loop;
  return result;
end;
$$;

/**
 * Top the caller up to `p_target` unredeemed codes and return all of them.
 *
 * Idempotent by construction: it counts what you already have and mints only the
 * difference, so the Invite screen can call it on every open without breeding
 * codes. The cap is enforced here rather than in the client precisely because
 * the client is the thing that would be looped.
 */
create or replace function public.my_invites(p_target int default 5)
returns table (code text, invitee_id text, redeemed_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid text := auth.uid()::text;
  have int;
  i int;
begin
  if uid is null then
    raise exception 'my_invites: no authenticated user';
  end if;
  -- Don't let a caller ask for a thousand codes.
  p_target := least(greatest(p_target, 0), 10);

  -- Aliased and qualified because RETURNS TABLE declares output variables named
  -- `code` / `invitee_id` / `redeemed_at`, which shadow the columns of the same
  -- name inside this body. Unqualified, `redeemed_at is null` is ambiguous.
  select count(*) into have
    from public.invites v where v.inviter_id = uid and v.redeemed_at is null;

  for i in 1..greatest(p_target - have, 0) loop
    insert into public.invites (code, inviter_id)
      values (public.generate_invite_code(), uid);
  end loop;

  return query
    select v.code, v.invitee_id, v.redeemed_at
      from public.invites v
     where v.inviter_id = uid
     order by v.redeemed_at nulls first, v.created_at;
end;
$$;

revoke all on function public.my_invites(int) from public, anon;
grant execute on function public.my_invites(int) to authenticated;

-- ============================================================
-- Redemption
-- ============================================================
/**
 * Claim a code. Returns the inviter's id on success, null if the code is
 * unusable — expired, already taken, your own, or simply wrong.
 *
 * It says "null" for all of those on purpose. Distinguishing "no such code" from
 * "already redeemed" would turn this into an oracle for testing codes against,
 * and a code is a bearer token.
 *
 * SECURITY DEFINER because this is the only path that may read a row by code
 * (there is no select-by-code policy) and the only path that may write one.
 */
create or replace function public.redeem_invite(p_code text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid text := auth.uid()::text;
  inviter text;
begin
  if uid is null then
    raise exception 'redeem_invite: no authenticated user';
  end if;

  -- Case- and whitespace-forgiving: this is typed by a human off a screenshot.
  p_code := upper(trim(p_code));

  -- FOR UPDATE is the whole race: two people pasting the same code at the same
  -- moment must not both be told yes. The row lock makes the second one wait and
  -- then see redeemed_at set.
  select v.inviter_id into inviter
    from public.invites v
   where v.code = p_code and v.redeemed_at is null
     for update;

  if inviter is null then return null; end if;
  if inviter = uid then return null; end if;  -- inviting yourself is not a referral

  -- One redemption per person, not per code: otherwise collecting links from ten
  -- friends would manufacture ten follows for someone who joined once.
  if exists (select 1 from public.invites where invitee_id = uid) then
    return null;
  end if;

  update public.invites
     set invitee_id = uid, redeemed_at = now()
   where code = p_code;

  -- The actual point: arrive already connected, in both directions. Written here
  -- rather than by the client because the invitee has no policy allowing them to
  -- make the INVITER follow them — nor should they; that power is exactly what
  -- this one narrow, audited path is for.
  insert into public.follows (follower_id, followee_id)
    values (uid, inviter), (inviter, uid)
    on conflict do nothing;

  -- Measured like any other funnel step (0027).
  insert into public.analytics_events (user_id, name, props)
    values (uid, 'invite_redeemed', jsonb_build_object('inviter', inviter));

  return inviter;
end;
$$;

revoke all on function public.redeem_invite(text) from public, anon;
grant execute on function public.redeem_invite(text) to authenticated;

-- Account deletion has to know about this table too (0020/0027's running list).
-- An invite is a row about two people, so deleting either end must not strand the
-- other: the inviter's codes go, and a redemption by the leaver is released back
-- to null rather than deleted, so the inviter's "3 left" stays truthful.
create or replace function public.delete_own_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid text := auth.uid()::text;
begin
  if uid is null then
    raise exception 'delete_own_account: no authenticated user';
  end if;

  delete from public.likes            where user_id = uid;
  delete from public.comments         where user_id = uid;
  delete from public.comparisons      where user_id = uid;
  delete from public.ratings          where user_id = uid;
  delete from public.diary_entries    where user_id = uid;
  delete from public.queue_items      where user_id = uid;
  delete from public.drops            where user_id = uid;
  delete from public.feed_events      where user_id = uid;
  delete from public.lists            where user_id = uid;
  delete from public.concert_tags     where user_id = uid;
  delete from public.concerts         where user_id = uid;
  delete from public.follows          where follower_id = uid or followee_id = uid;
  delete from public.blocks           where blocker_id = uid or blocked_id = uid;
  delete from public.reports          where reporter_id = uid or target_user_id = uid;
  delete from public.analytics_events where user_id = uid;
  delete from public.admins           where user_id = uid;

  -- Invites: drop the ones I handed out...
  delete from public.invites          where inviter_id = uid;
  -- ...and un-redeem the one I used, rather than deleting someone else's code.
  update public.invites
     set invitee_id = null, redeemed_at = null
   where invitee_id = uid;

  delete from public.profiles         where user_id = uid;

  -- The avatar is NOT deleted here. Supabase guards its storage tables with a
  -- `storage.protect_delete()` trigger that rejects direct DML ("Direct deletion
  -- from storage tables is not allowed. Use the Storage API instead."), so the
  -- line that used to live here didn't merely fail to remove the file — it threw,
  -- and took the whole account deletion down with it. It was there from 0020 and
  -- never once worked.
  --
  -- The client removes the avatar through the Storage API *before* calling this
  -- function, while the account still exists to authorize it (the bucket's RLS is
  -- owner-scoped). See SupabaseAuthBackend.removeAvatar.

  -- Still deliberately NOT touched: public.items (shared catalog cache).

  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_own_account() from public, anon;
grant execute on function public.delete_own_account() to authenticated;

-- ---------------------------------------------------------------------------
-- SELF-TEST — see 0021 for why these exist.
-- ---------------------------------------------------------------------------
do $$
declare
  inviter text := '00000000-0000-0000-0000-00000000e001';
  joiner  text := '00000000-0000-0000-0000-00000000e002';
  other   text := '00000000-0000-0000-0000-00000000e003';
  a_code  text;
  got     text;
  n       int;
begin
  perform set_config('request.jwt.claims', '', true);
  insert into public.profiles (user_id, display_name) values
    (inviter, 'Inviter Probe'), (joiner, 'Joiner Probe'), (other, 'Other Probe');

  -- ---- minting is idempotent -------------------------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', inviter)::text, true);
  perform public.my_invites(3);
  perform public.my_invites(3);
  select count(*) into n from public.invites where inviter_id = inviter;
  if n <> 3 then
    raise exception 'SELF-TEST FAILED: my_invites(3) called twice produced % codes, expected 3', n;
  end if;

  select code into a_code from public.invites where inviter_id = inviter limit 1;

  -- ---- you cannot redeem your own --------------------------------------
  got := public.redeem_invite(a_code);
  if got is not null then
    raise exception 'SELF-TEST FAILED: an inviter redeemed their own code';
  end if;

  -- ---- a real redemption links both directions -------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', joiner)::text, true);
  got := public.redeem_invite(lower('  ' || a_code || '  '));  -- messy input, as typed
  if got is distinct from inviter then
    raise exception 'SELF-TEST FAILED: redeem returned %, expected the inviter', got;
  end if;
  select count(*) into n
    from public.follows
   where (follower_id = joiner and followee_id = inviter)
      or (follower_id = inviter and followee_id = joiner);
  if n <> 2 then
    raise exception 'SELF-TEST FAILED: redemption created % follows, expected 2 (mutual)', n;
  end if;

  -- ---- a code is single-use ---------------------------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', other)::text, true);
  got := public.redeem_invite(a_code);
  if got is not null then
    raise exception 'SELF-TEST FAILED: a redeemed code was accepted a second time';
  end if;

  -- ---- one redemption per person ----------------------------------------
  -- The joiner already used one; a second, valid, different code must be refused.
  perform set_config('request.jwt.claims', json_build_object('sub', inviter)::text, true);
  select code into a_code from public.invites where inviter_id = inviter and redeemed_at is null limit 1;
  perform set_config('request.jwt.claims', json_build_object('sub', joiner)::text, true);
  got := public.redeem_invite(a_code);
  if got is not null then
    raise exception 'SELF-TEST FAILED: one person redeemed two codes — referral credit is farmable';
  end if;

  -- ---- a wrong code is silent, not an error -----------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', other)::text, true);
  got := public.redeem_invite('ZZZZZZ');
  if got is not null then
    raise exception 'SELF-TEST FAILED: a nonexistent code was accepted';
  end if;

  -- ---- minting tops up after a redemption -------------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', inviter)::text, true);
  perform public.my_invites(3);
  select count(*) into n from public.invites where inviter_id = inviter and redeemed_at is null;
  if n <> 3 then
    raise exception 'SELF-TEST FAILED: after a redemption, top-up left % unredeemed codes, expected 3', n;
  end if;

  -- ---- deleting the joiner releases the code, keeps the inviter whole ----
  -- No auth.users row is created for the probe: that table belongs to
  -- supabase_auth_admin and a real project refuses the insert, so a test that
  -- needed one would only ever pass on a local Postgres. delete_own_account's
  -- final DELETE is a harmless no-op for an id that was never an account, and
  -- every step before it — the part this asserts — still runs.
  perform set_config('request.jwt.claims', json_build_object('sub', joiner)::text, true);
  perform public.delete_own_account();
  select count(*) into n from public.invites where inviter_id = inviter;
  if n = 0 then
    raise exception 'SELF-TEST FAILED: deleting the invitee destroyed the inviter''s codes';
  end if;
  select count(*) into n from public.invites where invitee_id = joiner;
  if n <> 0 then
    raise exception 'SELF-TEST FAILED: a deleted account is still named on an invite';
  end if;

  perform set_config('request.jwt.claims', '', true);
  delete from public.invites where inviter_id = inviter;
  delete from public.follows where follower_id in (inviter, joiner, other) or followee_id in (inviter, joiner, other);
  delete from public.analytics_events where user_id in (inviter, joiner, other);
  delete from public.profiles where user_id in (inviter, joiner, other);

  raise notice 'Invites self-test passed.';
end;
$$;
